services:
  rabbitmq:
    container_name: rabbitmq_ec
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins